### ISSUE TITLE
Start the task after all the startup tasks are completed

### ISSUE THREAD

**Issue by vengi83644** [dotnet-labs/ServiceWorkerCronJob#5]
Is is possible to do this?

I am accessing the Configuration in my DoWork.

**Comment by changhuixu** [comment]
Hi @vengi83644 ,
The `HostedService` jobs will start as the application starts. And, the `Configuration` is a singleton, which should be available if you inject it to your class.
What do you mean "after all the startup tasks" and ""accessing the Configuration"? 
Could you elaborate your question a little bit more?

**Comment by vengi83644** [comment]
Never mind. Sorry. My bad.
